id: AD5776CCB
base_file: f8158.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:55:29.992288
  last_modified_at: 2022-05-31 06:55:29.992291
