id: AD5776CCB
base_file: f9241.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:55:29.993473
  last_modified_at: 2022-05-31 06:55:29.993493
