id: AD5776CCB
base_file: fFF55.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:55:29.995899
  last_modified_at: 2022-05-31 06:55:29.995903
